apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-canary
  namespace: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
      version: canary
  template:
    metadata:
      labels:
        app: python-app
        version: canary
    spec:
      containers:
      - name: python-app
        image: python-app:canary   # Local image name
        imagePullPolicy: Never    # Tells Kubernetes to use the local image
        ports:
        - containerPort: 5001
