apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-stable
  namespace: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
      version: stable
  template:
    metadata:
      labels:
        app: python-app
        version: stable
    spec:
      containers:
      - name: python-app
        image: python-app:stable   # Local image name
        imagePullPolicy: Never    # Tells Kubernetes to use the local image
        ports:
        - containerPort: 5001
